language: node_js

script:
  - node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --compilers coffee:coffee-script/register
  - cat coverage/lcov.info | node_modules/.bin/coveralls
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
os:
  - linux
  - osx

notifications:
  slack:
    secure: kwqR/QqTp02xCQPU33yTphvzFf7xIJv/ry1By9Np8hSuH4JQk+Ud5sypxQtqq9h6owlL2OG2f5uhVTHdaQeR/sKE6A25n3Im4SQXBjy8cFk9O3m+AaS1pY7UeevNU2LfOIdsN9Rs+/VNXTEXw9+eD+k1UiINcJUOtZtHZDfAYzbz2m4tyI/6ISUUSWK//X0ixzdRzjNlajNwIboubOF9kihfOqrrI90io9UG1nwp0rwNdiXQjMM+DJsvtp6nG4f96MlbdvlNhc+Oq/9JgeGp4WgaCrC45ZzrEaPOWJcm2y2/RMTUiO+1+r3JlbeL8DtHwq6V77zO0DPKDsZvKfRwW2RSJQwq5HB6bDBsvtgdtnnWWeFWC6YMKT0EQ10+Gg1WxyK5XzuZNxBX6iGc5o23PmgV/ERHJ5bnwUtm3qfSHvrc0FRxaWQMZLWPUbcQWkD/JZ7aTfZxbgGlllkj8YwywFyk8E7DP3u5/f5/rfEEjV4AUKS7jch5wcFtTu0y7MaKF7HuKkQc6ip1RL4s4gikm2FQLmhd7YYjXDCueaeF54Sk1rqwrPp0YNDesuI6QpmKNlPmYTj8Bv5EihmYJRauN5SYC867OfbmMfE8FFhtBUXuTnZL7Zdp86MDtrhmsf01ntl7Quoe6HhQBOL/6ulJlWbADCDXr0xCbof9nWWLqXc=
